/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary":                    "#b4ccbb",
        "on-primary":                 "#203529",
        "primary-container":          "#1a2f23",
        "on-primary-container":       "#809787",
        "primary-fixed":              "#d0e9d6",
        "primary-fixed-dim":          "#b4ccbb",
        "on-primary-fixed":           "#0a2014",
        "on-primary-fixed-variant":   "#364c3e",
        "secondary":                  "#d7c3b0",
        "on-secondary":               "#3a2e21",
        "secondary-container":        "#544738",
        "on-secondary-container":     "#c8b5a3",
        "secondary-fixed":            "#f4dfcb",
        "secondary-fixed-dim":        "#d7c3b0",
        "on-secondary-fixed":         "#241a0e",
        "on-secondary-fixed-variant": "#524436",
        "tertiary":                   "#e7beae",
        "on-tertiary":                "#442a20",
        "tertiary-container":         "#3d241a",
        "on-tertiary-container":      "#af8a7c",
        "tertiary-fixed":             "#ffdbce",
        "tertiary-fixed-dim":         "#e7beae",
        "on-tertiary-fixed":          "#2c160c",
        "on-tertiary-fixed-variant":  "#5d4034",
        "error":                      "#ffb4ab",
        "on-error":                   "#690005",
        "error-container":            "#93000a",
        "on-error-container":         "#ffdad6",
        "background":                 "#121411",
        "on-background":              "#e3e3de",
        "surface":                    "#121411",
        "on-surface":                 "#e3e3de",
        "surface-variant":            "#333532",
        "on-surface-variant":         "#c2c8c2",
        "surface-dim":                "#121411",
        "surface-bright":             "#383a36",
        "surface-container-lowest":   "#0d0f0c",
        "surface-container-low":      "#1a1c19",
        "surface-container":          "#1e201d",
        "surface-container-high":     "#292a27",
        "surface-container-highest":  "#333532",
        "surface-tint":               "#b4ccbb",
        "inverse-surface":            "#e3e3de",
        "inverse-on-surface":         "#2f312e",
        "inverse-primary":            "#4d6355",
        "outline":                    "#8c928c",
        "outline-variant":            "#424843",
      },
      fontFamily: {
        sans: ["Manrope", "sans-serif"],
        headline: ["Hanken Grotesk", "sans-serif"],
        mono: ["Geist", "monospace"],
      },
      spacing: {
        "xs":     "0.5rem",
        "sm":     "1rem",
        "md":     "1.5rem",
        "lg":     "2.5rem",
        "xl":     "4rem",
        "gutter": "24px",
        "margin": "32px",
      },
      borderRadius: {
        "sm":  "0.125rem",
        "DEFAULT": "0.5rem",
        "lg":  "0.75rem",
        "xl":  "1rem",
        "2xl": "1.5rem",
        "full": "9999px",
      },
    },
  },
  plugins: [],
};
